(() => {
  const CONFIG_ENDPOINT = 'https://pvpgvzaasnkukhoziiyg.supabase.co/functions/v1/academy-public-config';
  const authView = document.querySelector('[data-auth-view]');
  const dashboard = document.querySelector('[data-dashboard]');
  const statusEl = document.querySelector('[data-auth-status]');
  const loginForm = document.querySelector('[data-login-form]');
  const magicBtn = document.querySelector('[data-magic-link]');
  const signoutBtn = document.querySelector('[data-signout]');
  let sb, workspace, membership, workspaceSlug = 'yamilet-mes';
  const setStatus=(text,ok=false)=>{if(!statusEl)return;statusEl.textContent=text||'';statusEl.classList.toggle('ok',!!ok)};
  const escapeHtml=(value='')=>String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const formatDate=value=>new Intl.DateTimeFormat('es-MX',{day:'2-digit',month:'short',year:'numeric',timeZone:'UTC'}).format(new Date(`${value}T12:00:00Z`));
  async function initSupabase(){const res=await fetch(CONFIG_ENDPOINT,{headers:{Accept:'application/json'}});if(!res.ok)throw new Error('config');const cfg=await res.json();workspaceSlug=cfg.workspaceSlug||workspaceSlug;sb=window.supabase.createClient(cfg.url,cfg.anonKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}})}
  async function loadDashboard(user){authView.classList.add('hidden');dashboard.classList.remove('hidden');const [{data:profile},{data:ws,error:wsError}]=await Promise.all([sb.from('profiles').select('full_name,role,email').eq('id',user.id).maybeSingle(),sb.from('workspaces').select('id,name,slug,accent_color').eq('slug',workspaceSlug).maybeSingle()]);if(wsError||!ws){document.querySelector('[data-user-role]').textContent='No se encontró Academia Yamilet.';return}workspace=ws;const {data:member}=await sb.from('workspace_members').select('role,status').eq('workspace_id',ws.id).eq('user_id',user.id).maybeSingle();membership=member;document.querySelector('[data-user-name]').textContent=profile?.full_name||user.email?.split('@')[0]||'Alumno';document.querySelector('[data-user-role]').textContent=`${ws.name} · ${member?.role||profile?.role||'alumno'}`;await Promise.all([loadCourses(),loadBookings(profile)])}
  async function loadCourses(){const list=document.querySelector('[data-course-list]'),count=document.querySelector('[data-course-count]');const {data,error}=await sb.from('courses').select('id,title,subtitle,description,status,instructor_name,duration_label').eq('workspace_id',workspace.id).order('created_at',{ascending:true});if(error){list.innerHTML='<div class="empty">No fue posible cargar los cursos.</div>';return}count.textContent=data?.length||0;if(!data?.length){list.innerHTML='<div class="empty">Los cursos aparecerán aquí conforme se publiquen.</div>';return}list.innerHTML=data.map(c=>`<article class="course-card"><span class="tag">${c.status==='published'?'Publicado':'En preparación'}</span><h3>${escapeHtml(c.title)}</h3><p>${escapeHtml(c.subtitle||c.description||'Contenido de Academia Yamilet.')}</p><p><strong>Instructora:</strong> ${escapeHtml(c.instructor_name||'Yamilet Pérez')}</p></article>`).join('')}
  async function loadBookings(profile){const list=document.querySelector('[data-booking-list]'),count=document.querySelector('[data-booking-count]');const isManager=(membership&&['owner','admin'].includes(membership.role))||profile?.role==='admin';if(!isManager){list.innerHTML='<div class="empty">Esta sección es visible para administradores.</div>';count.textContent='—';return}const {data,error}=await sb.from('free_class_bookings').select('id,requested_date,name,email,status').eq('workspace_id',workspace.id).order('requested_date',{ascending:true}).limit(100);if(error){list.innerHTML='<div class="empty">No fue posible cargar las reservaciones.</div>';return}count.textContent=(data||[]).filter(x=>x.status==='pending').length;if(!data?.length){list.innerHTML='<div class="empty">Todavía no hay solicitudes de clase gratuita.</div>';return}list.innerHTML=data.map(b=>`<article class="booking-row"><strong>${formatDate(b.requested_date)}</strong><span>${escapeHtml(b.name)}</span><span>${escapeHtml(b.email)}</span><select data-booking-status="${b.id}"><option value="pending" ${b.status==='pending'?'selected':''}>Pendiente</option><option value="confirmed" ${b.status==='confirmed'?'selected':''}>Confirmada</option><option value="completed" ${b.status==='completed'?'selected':''}>Completada</option><option value="cancelled" ${b.status==='cancelled'?'selected':''}>Cancelada</option></select></article>`).join('');list.querySelectorAll('[data-booking-status]').forEach(select=>select.addEventListener('change',async()=>{select.disabled=true;const {error:updateError}=await sb.from('free_class_bookings').update({status:select.value}).eq('id',select.dataset.bookingStatus);select.disabled=false;if(updateError)alert('No fue posible actualizar la reservación.');else loadBookings(profile)}))}
  async function start(){try{await initSupabase();loginForm?.addEventListener('submit',async e=>{e.preventDefault();setStatus('Validando acceso…');const fd=new FormData(loginForm);const {data,error}=await sb.auth.signInWithPassword({email:String(fd.get('email')||'').trim().toLowerCase(),password:String(fd.get('password')||'')});if(error){setStatus('No se pudo iniciar sesión. Revisa tus datos o usa el enlace seguro por correo.');return}setStatus('Acceso correcto.',true);await loadDashboard(data.user)});magicBtn?.addEventListener('click',async()=>{const email=String(loginForm?.querySelector('input[name=email]')?.value||'').trim().toLowerCase();if(!email){setStatus('Escribe primero tu correo.');return}setStatus('Enviando enlace seguro…');const redirectTo=new URL('./',window.location.href).href;const {error}=await sb.auth.signInWithOtp({email,options:{emailRedirectTo:redirectTo,shouldCreateUser:false}});if(error){setStatus('No fue posible enviar el enlace. Verifica que el correo esté registrado.');return}setStatus('Revisa tu correo. Te enviamos un enlace de acceso.',true)});signoutBtn?.addEventListener('click',async()=>{await sb.auth.signOut();location.reload()});document.querySelector('[data-scroll-courses]')?.addEventListener('click',()=>document.querySelector('#mis-cursos')?.scrollIntoView({behavior:'smooth'}));document.querySelector('[data-scroll-bookings]')?.addEventListener('click',()=>document.querySelector('#reservas')?.scrollIntoView({behavior:'smooth'}));sb.auth.onAuthStateChange((_event,session)=>{if(session?.user&&dashboard.classList.contains('hidden'))loadDashboard(session.user)});const {data}=await sb.auth.getSession();if(data.session?.user)loadDashboard(data.session.user)}catch(err){setStatus('No fue posible conectar con Academia Yamilet. Intenta nuevamente en unos minutos.')}}
  start();
})();
