-- Academia Yamilet v25: comunidad, soporte y actividad reciente
-- La actividad se calcula desde fuentes existentes para evitar un segundo historial duplicado.

create or replace function private.can_access_academy_workspace(target_workspace uuid)
returns boolean language sql stable security definer set search_path=''
as $$ select (select auth.uid()) is not null and (private.is_admin() or exists(select 1 from public.workspace_members wm where wm.workspace_id=target_workspace and wm.user_id=(select auth.uid()) and wm.status='active') or exists(select 1 from public.enrollments e join public.courses c on c.id=e.course_id where e.user_id=(select auth.uid()) and e.status in ('active','completed') and c.workspace_id=target_workspace)); $$;

create or replace function private.can_manage_academy_workspace(target_workspace uuid)
returns boolean language sql stable security definer set search_path=''
as $$ select private.is_admin() or exists(select 1 from public.workspace_members wm where wm.workspace_id=target_workspace and wm.user_id=(select auth.uid()) and wm.status='active' and wm.role in ('owner','admin','instructor')); $$;

create or replace function private.can_access_academy_community(target_course uuid)
returns boolean language sql stable security definer set search_path=''
as $$ select (select auth.uid()) is not null and (exists(select 1 from public.enrollments e where e.user_id=(select auth.uid()) and e.course_id=target_course and e.status in ('active','completed')) or private.can_manage_academy_course(target_course)); $$;

drop policy if exists academy_community_threads_select on public.academy_community_threads;
drop policy if exists academy_community_threads_insert on public.academy_community_threads;
drop policy if exists academy_community_replies_select on public.academy_community_replies;
drop policy if exists academy_community_replies_insert on public.academy_community_replies;
create policy academy_community_threads_select on public.academy_community_threads for select to authenticated using (private.can_access_academy_community(course_id) and (status<>'hidden' or private.can_manage_academy_course(course_id)));
create policy academy_community_threads_insert on public.academy_community_threads for insert to authenticated with check (user_id=(select auth.uid()) and private.can_access_academy_community(course_id) and (lesson_id is null or exists(select 1 from public.lessons l join public.modules m on m.id=l.module_id where l.id=academy_community_threads.lesson_id and m.course_id=academy_community_threads.course_id)));
create policy academy_community_replies_select on public.academy_community_replies for select to authenticated using (exists(select 1 from public.academy_community_threads t where t.id=academy_community_replies.thread_id and private.can_access_academy_community(t.course_id) and (t.status<>'hidden' or private.can_manage_academy_course(t.course_id))));
create policy academy_community_replies_insert on public.academy_community_replies for insert to authenticated with check (user_id=(select auth.uid()) and exists(select 1 from public.academy_community_threads t where t.id=academy_community_replies.thread_id and t.status='open' and private.can_access_academy_community(t.course_id)));

create or replace function private.set_academy_community_thread_author() returns trigger language plpgsql security definer set search_path=''
as $$ declare uid uuid:=coalesce((select auth.uid()),new.user_id); workspace_value uuid; display_name text; workspace_role text; begin if uid is null then raise exception 'Usuario requerido'; end if; new.user_id:=uid; select c.workspace_id into workspace_value from public.courses c where c.id=new.course_id; select coalesce(nullif(trim(p.full_name),''),nullif(trim(p.email),''),'Alumna de Academia Yamilet') into display_name from public.profiles p where p.id=uid; select wm.role into workspace_role from public.workspace_members wm where wm.workspace_id=workspace_value and wm.user_id=uid and wm.status='active' limit 1; new.author_name:=coalesce(display_name,'Alumna de Academia Yamilet'); new.author_role:=coalesce(workspace_role,(select p.role from public.profiles p where p.id=uid),'student'); return new; end; $$;
drop trigger if exists community_thread_set_author on public.academy_community_threads;
create trigger community_thread_set_author before insert on public.academy_community_threads for each row execute function private.set_academy_community_thread_author();

create or replace function private.set_academy_community_reply_author() returns trigger language plpgsql security definer set search_path=''
as $$ declare uid uuid:=coalesce((select auth.uid()),new.user_id); workspace_value uuid; display_name text; workspace_role text; begin if uid is null then raise exception 'Usuario requerido'; end if; new.user_id:=uid; select c.workspace_id into workspace_value from public.academy_community_threads t join public.courses c on c.id=t.course_id where t.id=new.thread_id; select coalesce(nullif(trim(p.full_name),''),nullif(trim(p.email),''),'Alumna de Academia Yamilet') into display_name from public.profiles p where p.id=uid; select wm.role into workspace_role from public.workspace_members wm where wm.workspace_id=workspace_value and wm.user_id=uid and wm.status='active' limit 1; new.author_name:=coalesce(display_name,'Alumna de Academia Yamilet'); new.author_role:=coalesce(workspace_role,(select p.role from public.profiles p where p.id=uid),'student'); return new; end; $$;
drop trigger if exists community_reply_set_author on public.academy_community_replies;
create trigger community_reply_set_author before insert on public.academy_community_replies for each row execute function private.set_academy_community_reply_author();

create or replace function private.notify_academy_community_thread() returns trigger language plpgsql security definer set search_path=''
as $$ declare workspace_value uuid; staff record; begin select c.workspace_id into workspace_value from public.courses c where c.id=new.course_id; for staff in select wm.user_id from public.workspace_members wm where wm.workspace_id=workspace_value and wm.status='active' and wm.role in ('owner','admin','instructor') and wm.user_id<>new.user_id loop perform private.enqueue_academy_notification(staff.user_id,'community_thread','Nueva conversación en Comunidad',new.title,'#community/'||new.id::text,'community_thread',new.id,'community-thread:'||new.id::text||':'||staff.user_id::text); end loop; return new; end; $$;
drop trigger if exists community_thread_notification on public.academy_community_threads;
create trigger community_thread_notification after insert on public.academy_community_threads for each row execute function private.notify_academy_community_thread();

create or replace function private.notify_academy_community_reply() returns trigger language plpgsql security definer set search_path=''
as $$ declare owner_user uuid; thread_title text; begin select t.user_id,t.title into owner_user,thread_title from public.academy_community_threads t where t.id=new.thread_id; if owner_user is not null and owner_user<>new.user_id then perform private.enqueue_academy_notification(owner_user,'community_reply','Nueva respuesta en Comunidad',coalesce(thread_title,'Tu conversación')||' recibió una nueva respuesta.','#community/'||new.thread_id::text,'community_thread',new.thread_id,'community-reply:'||new.id::text); end if; return new; end; $$;
drop trigger if exists community_reply_notification on public.academy_community_replies;
create trigger community_reply_notification after insert on public.academy_community_replies for each row execute function private.notify_academy_community_reply();

create or replace function private.set_academy_community_thread_status(target_thread uuid,new_status text) returns void language plpgsql security definer set search_path=''
as $$ declare t public.academy_community_threads%rowtype; manager boolean; begin if (select auth.uid()) is null then raise exception 'Autenticación requerida'; end if; if new_status not in ('open','resolved','hidden') then raise exception 'Estado inválido'; end if; select * into t from public.academy_community_threads where id=target_thread; if not found then raise exception 'Conversación no encontrada'; end if; manager:=private.can_manage_academy_course(t.course_id); if new_status='hidden' and not manager then raise exception 'No autorizado'; end if; if new_status in ('open','resolved') and not (manager or t.user_id=(select auth.uid())) then raise exception 'No autorizado'; end if; update public.academy_community_threads set status=new_status,updated_at=now() where id=target_thread; end; $$;
create or replace function public.set_academy_community_thread_status(target_thread uuid,new_status text) returns void language sql set search_path='' as $$ select private.set_academy_community_thread_status(target_thread,new_status); $$;
revoke all on function public.set_academy_community_thread_status(uuid,text) from public,anon;
grant execute on function public.set_academy_community_thread_status(uuid,text) to authenticated;

create table if not exists public.academy_support_tickets(id uuid primary key default gen_random_uuid(),workspace_id uuid not null references public.workspaces(id) on delete cascade,user_id uuid not null references auth.users(id) on delete cascade,course_id uuid null references public.courses(id) on delete set null,subject text not null check(char_length(btrim(subject)) between 3 and 160),category text not null default 'academic' check(category in ('academic','technical','access','billing','other')),priority text not null default 'normal' check(priority in ('low','normal','high')),status text not null default 'open' check(status in ('open','in_progress','waiting_user','resolved','closed')),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),last_message_at timestamptz not null default now(),closed_at timestamptz null);
create table if not exists public.academy_support_messages(id uuid primary key default gen_random_uuid(),ticket_id uuid not null references public.academy_support_tickets(id) on delete cascade,user_id uuid not null references auth.users(id) on delete cascade,author_name text not null,author_role text not null default 'student',body text not null check(char_length(btrim(body)) between 1 and 5000),created_at timestamptz not null default now());
create index if not exists academy_support_tickets_workspace_status_idx on public.academy_support_tickets(workspace_id,status,last_message_at desc);
create index if not exists academy_support_tickets_user_idx on public.academy_support_tickets(user_id,last_message_at desc);
create index if not exists academy_support_messages_ticket_idx on public.academy_support_messages(ticket_id,created_at);
alter table public.academy_support_tickets enable row level security;
alter table public.academy_support_messages enable row level security;

create or replace function private.can_read_academy_support_ticket(target_ticket uuid) returns boolean language sql stable security definer set search_path='' as $$ select exists(select 1 from public.academy_support_tickets t where t.id=target_ticket and (t.user_id=(select auth.uid()) or private.can_manage_academy_workspace(t.workspace_id))); $$;
drop policy if exists academy_support_tickets_select on public.academy_support_tickets;
drop policy if exists academy_support_tickets_insert on public.academy_support_tickets;
drop policy if exists academy_support_tickets_update_staff on public.academy_support_tickets;
create policy academy_support_tickets_select on public.academy_support_tickets for select to authenticated using(user_id=(select auth.uid()) or private.can_manage_academy_workspace(workspace_id));
create policy academy_support_tickets_insert on public.academy_support_tickets for insert to authenticated with check(user_id=(select auth.uid()) and private.can_access_academy_workspace(workspace_id) and (course_id is null or exists(select 1 from public.courses c where c.id=academy_support_tickets.course_id and c.workspace_id=academy_support_tickets.workspace_id and (private.can_manage_academy_course(c.id) or exists(select 1 from public.enrollments e where e.user_id=(select auth.uid()) and e.course_id=c.id and e.status in ('active','completed'))))));
create policy academy_support_tickets_update_staff on public.academy_support_tickets for update to authenticated using(private.can_manage_academy_workspace(workspace_id)) with check(private.can_manage_academy_workspace(workspace_id));
drop policy if exists academy_support_messages_select on public.academy_support_messages;
drop policy if exists academy_support_messages_insert on public.academy_support_messages;
create policy academy_support_messages_select on public.academy_support_messages for select to authenticated using(private.can_read_academy_support_ticket(ticket_id));
create policy academy_support_messages_insert on public.academy_support_messages for insert to authenticated with check(user_id=(select auth.uid()) and private.can_read_academy_support_ticket(ticket_id));
revoke all on public.academy_support_tickets from anon;
revoke all on public.academy_support_messages from anon;
grant select,insert,update on public.academy_support_tickets to authenticated;
grant select,insert on public.academy_support_messages to authenticated;

create or replace function private.set_academy_support_message_author() returns trigger language plpgsql security definer set search_path=''
as $$ declare uid uuid:=coalesce((select auth.uid()),new.user_id); ticket_workspace uuid; display_name text; workspace_role text; begin if uid is null then raise exception 'Usuario requerido'; end if; new.user_id:=uid; select t.workspace_id into ticket_workspace from public.academy_support_tickets t where t.id=new.ticket_id; select coalesce(nullif(trim(p.full_name),''),nullif(trim(p.email),''),'Usuario de Academia Yamilet') into display_name from public.profiles p where p.id=uid; select wm.role into workspace_role from public.workspace_members wm where wm.workspace_id=ticket_workspace and wm.user_id=uid and wm.status='active' limit 1; new.author_name:=coalesce(display_name,'Usuario de Academia Yamilet'); new.author_role:=coalesce(workspace_role,(select p.role from public.profiles p where p.id=uid),'student'); return new; end; $$;
drop trigger if exists support_message_set_author on public.academy_support_messages;
create trigger support_message_set_author before insert on public.academy_support_messages for each row execute function private.set_academy_support_message_author();

create or replace function private.notify_academy_support_ticket() returns trigger language plpgsql security definer set search_path=''
as $$ declare staff record; begin for staff in select wm.user_id from public.workspace_members wm where wm.workspace_id=new.workspace_id and wm.status='active' and wm.role in ('owner','admin','instructor') and wm.user_id<>new.user_id loop perform private.enqueue_academy_notification(staff.user_id,'support_new','Nueva solicitud de soporte',new.subject,'#support/'||new.id::text,'support_ticket',new.id,'support-ticket:'||new.id::text||':'||staff.user_id::text); end loop; return new; end; $$;
drop trigger if exists support_ticket_notification on public.academy_support_tickets;
create trigger support_ticket_notification after insert on public.academy_support_tickets for each row execute function private.notify_academy_support_ticket();

create or replace function private.after_academy_support_message() returns trigger language plpgsql security definer set search_path=''
as $$ declare ticket_row public.academy_support_tickets%rowtype; sender_staff boolean:=false; staff record; begin select * into ticket_row from public.academy_support_tickets where id=new.ticket_id; sender_staff:=private.can_manage_academy_workspace(ticket_row.workspace_id); update public.academy_support_tickets set last_message_at=new.created_at,updated_at=now(),status=case when sender_staff and status='open' then 'in_progress' when not sender_staff and status='waiting_user' then 'open' else status end where id=new.ticket_id; if sender_staff then if ticket_row.user_id<>new.user_id then perform private.enqueue_academy_notification(ticket_row.user_id,'support_reply','Soporte respondió tu solicitud',ticket_row.subject,'#support/'||ticket_row.id::text,'support_ticket',ticket_row.id,'support-message:'||new.id::text||':owner'); end if; else for staff in select wm.user_id from public.workspace_members wm where wm.workspace_id=ticket_row.workspace_id and wm.status='active' and wm.role in ('owner','admin','instructor') and wm.user_id<>new.user_id loop perform private.enqueue_academy_notification(staff.user_id,'support_reply','Nueva respuesta en soporte',ticket_row.subject,'#support/'||ticket_row.id::text,'support_ticket',ticket_row.id,'support-message:'||new.id::text||':'||staff.user_id::text); end loop; end if; return new; end; $$;
drop trigger if exists support_message_after_insert on public.academy_support_messages;
create trigger support_message_after_insert after insert on public.academy_support_messages for each row execute function private.after_academy_support_message();

create or replace function private.set_academy_support_ticket_status_impl(target_ticket uuid,target_status text) returns text language plpgsql security definer set search_path=''
as $$ declare t public.academy_support_tickets%rowtype; begin if (select auth.uid()) is null then raise exception 'Autenticación requerida'; end if; if target_status not in ('open','in_progress','waiting_user','resolved','closed') then raise exception 'Estado no válido'; end if; select * into t from public.academy_support_tickets where id=target_ticket; if not found then raise exception 'Solicitud no encontrada'; end if; if not private.can_manage_academy_workspace(t.workspace_id) then raise exception 'No autorizado'; end if; update public.academy_support_tickets set status=target_status,updated_at=now(),closed_at=case when target_status in ('resolved','closed') then now() else null end where id=target_ticket; if target_status in ('resolved','closed') then perform private.enqueue_academy_notification(t.user_id,'support_status','Actualización de soporte',t.subject||' · '||target_status,'#support/'||t.id::text,'support_ticket',t.id,'support-status:'||t.id::text||':'||target_status); end if; return target_status; end; $$;
create or replace function public.set_academy_support_ticket_status(target_ticket uuid,target_status text) returns text language sql set search_path='' as $$ select private.set_academy_support_ticket_status_impl(target_ticket,target_status); $$;
revoke all on function public.set_academy_support_ticket_status(uuid,text) from public,anon;
grant execute on function public.set_academy_support_ticket_status(uuid,text) to authenticated;

create or replace function public.get_academy_recent_activity(target_workspace uuid,limit_count integer default 20)
returns table(activity_type text,title text,detail text,occurred_at timestamptz,target_path text)
language plpgsql security definer set search_path=''
as $$ declare uid uuid:=(select auth.uid()); cap integer:=greatest(1,least(coalesce(limit_count,20),50)); begin if uid is null then raise exception 'Autenticación requerida'; end if; if not private.can_access_academy_workspace(target_workspace) then raise exception 'No autorizado'; end if; return query select x.activity_type,x.title,x.detail,x.occurred_at,x.target_path from (select 'lesson_completed'::text,'Lección completada'::text,l.title||' · '||c.title,coalesce(lp.completed_at,lp.updated_at),'#course/'||c.id::text from public.lesson_progress lp join public.lessons l on l.id=lp.lesson_id join public.modules m on m.id=l.module_id join public.courses c on c.id=m.course_id where lp.user_id=uid and lp.completed=true and c.workspace_id=target_workspace union all select case when aa.passed then 'assessment_passed' else 'assessment_attempt' end,case when aa.passed then 'Evaluación aprobada' else 'Evaluación enviada' end,a.title||' · '||c.title,coalesce(aa.graded_at,aa.submitted_at,aa.started_at),'#assessment/'||a.id::text from public.assessment_attempts aa join public.assessments a on a.id=aa.assessment_id join public.courses c on c.id=a.course_id where aa.user_id=uid and c.workspace_id=target_workspace and aa.status in ('submitted','graded') union all select 'certificate_ready','Certificado emitido',c.title,cert.issued_at,'#certificate/'||c.id::text from public.certificates cert join public.courses c on c.id=cert.course_id where cert.user_id=uid and cert.revoked_at is null and c.workspace_id=target_workspace union all select 'course_assigned','Curso asignado',c.title,e.enrolled_at,'#course/'||c.id::text from public.enrollments e join public.courses c on c.id=e.course_id where e.user_id=uid and c.workspace_id=target_workspace union all select 'community_thread','Conversación creada',t.title,t.created_at,'#community/'||t.id::text from public.academy_community_threads t join public.courses c on c.id=t.course_id where t.user_id=uid and c.workspace_id=target_workspace and t.status<>'hidden' union all select 'community_reply','Respuesta en Comunidad',t.title,r.created_at,'#community/'||t.id::text from public.academy_community_replies r join public.academy_community_threads t on t.id=r.thread_id join public.courses c on c.id=t.course_id where r.user_id=uid and c.workspace_id=target_workspace and t.status<>'hidden' union all select 'support_ticket','Solicitud de soporte',t.subject,t.created_at,'#support/'||t.id::text from public.academy_support_tickets t where t.user_id=uid and t.workspace_id=target_workspace union all select 'support_reply','Actividad en soporte',t.subject,m.created_at,'#support/'||t.id::text from public.academy_support_messages m join public.academy_support_tickets t on t.id=m.ticket_id where t.user_id=uid and t.workspace_id=target_workspace) x where x.occurred_at is not null order by x.occurred_at desc limit cap; end; $$;
revoke all on function public.get_academy_recent_activity(uuid,integer) from public,anon;
grant execute on function public.get_academy_recent_activity(uuid,integer) to authenticated;
